# Find The executable of timeout executable

IF (TIMEOUT_EXECUTABLE)
  SET(TIMEOUT_FOUND TRUE)
ENDIF (TIMEOUT_EXECUTABLE)

FIND_PROGRAM(TIMEOUT_EXECUTABLE NAMES timeout gtimeout
				DOC "timeout from coreutils")

IF (TIMEOUT_EXECUTABLE)
  SET (TIMEOUT_FOUND TRUE)
ELSE ()
  SET (TIMEOUT_FOUND FALSE)
ENDIF (TIMEOUT_EXECUTABLE)

IF (TIMEOUT_FOUND)
  IF (NOT TIMEOUT_FIND_QUIETLY)
    MESSAGE(STATUS "Found timeout: ${TIMEOUT_EXECUTABLE}")
  ENDIF (NOT TIMEOUT_FIND_QUIETLY)

ELSE ()
  IF (TIMEOUT_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find timeout!")
  ENDIF()
ENDIF()
