# Find The executable of Boolector SMT solver

IF (Z3_EXECUTABLE)
  SET(Z3_FOUND TRUE)
ENDIF (Z3_EXECUTABLE)

FIND_PROGRAM(Z3_EXECUTABLE NAMES z3 DOC "z3 Executable")
MARK_AS_ADVANCED(Z3_EXECUTABLE)

IF (Z3_EXECUTABLE)
  SET (Z3_FOUND TRUE)
  SET (SOLVER_EXECUTABLE ${Z3_EXECUTABLE})
  SET (SOLVER_FLAGS "-smt")
  SET (SOLVER_DIAGNOSE_FLAGS "-m")
ELSE ()
  SET (Z3_FOUND FALSE)
ENDIF (Z3_EXECUTABLE)

IF (Z3_FOUND)
  IF (NOT Z3_FIND_QUIETLY)
    MESSAGE(STATUS "Found Z3: ${Z3_EXECUTABLE}")
  ENDIF (NOT Z3_FIND_QUIETLY)

ELSE ()
  IF (Z3_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find Z3!")
  ENDIF()
ENDIF()


