# Find The executable of Boolector SMT solver

IF (BOOLECTOR_EXECUTABLE)
  SET(BOOLECTOR_FOUND TRUE)
ENDIF (BOOLECTOR_EXECUTABLE)

FIND_PROGRAM(BOOLECTOR_EXECUTABLE NAMES boolector DOC "Boolector Executable")
MARK_AS_ADVANCED(BOOLECTOR_EXECUTABLE)

IF (BOOLECTOR_EXECUTABLE)
  SET (BOOLECTOR_FOUND TRUE)
  SET (SOLVER_EXECUTABLE ${BOOLECTOR_EXECUTABLE})
  SET (SOLVER_FLAGS "--smt")
  SET (SOLVER_DIAGNOSE_FLAGS "-m -x")
ELSE ()
  SET (BOOLECTOR_FOUND FALSE)
ENDIF (BOOLECTOR_EXECUTABLE)

IF (BOOLECTOR_FOUND)
  IF (NOT BOOLECTOR_FIND_QUIETLY)
    MESSAGE(STATUS "Found boolector: ${BOOLECTOR_EXECUTABLE}")
  ENDIF (NOT BOOLECTOR_FIND_QUIETLY)

ELSE ()
  IF (Boolector_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find Boolector!")
  ENDIF()
ENDIF()


